# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('w_number', models.CharField(max_length=8)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SuperHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1)),
                ('article', models.CharField(choices=[(b'A', b'A'), (b'An', b'An'), (b'The', b'The')], max_length=3)),
                ('literature_from', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=2000)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='person',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.SuperHero'),
        ),
    ]
