# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180620_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='w_number',
            field=models.CharField(blank=True, default=b'', max_length=8),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='desc',
            field=models.CharField(blank=True, default=b'', max_length=2000),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default=b'M', max_length=1),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='literature_from',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
