# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180620_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default=b'M', max_length=1),
        ),
    ]
