# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180621_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('refresh_token', models.TextField()),
                ('updated_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
