# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180621_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hero',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polls.SuperHero'),
        ),
    ]
