# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_level',
            field=models.IntegerField(default=1),
        ),
    ]
