# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180621_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_birthday_email_sent_on_year',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
